### ISSUE TITLE
Frames with missing landmarks prevent transcription

### ISSUE THREAD

**Issue by marekjg** [wissemkarous/End-of-year-Project#1]
Hi, first of all: great project! I want to use it as a starting point for classification problem and I wonder what was the pipeline. When I use inference.py it fails on videos where are some frames without landmarks and it happens a lot in my dataset (although the face is roughly in the same spot). Did it happen when you were training the model? Should I just use some interpolation for landmarks for missing frames?

Thanks,
Marek

**Comment by wissemkarous** [comment]
Thank you for your kind words and for your interest in our project! I'm glad to hear you're considering it for your classification problem. During our training phase, we didn't experience frequent issues with frames lacking landmarks. This could be due to differences in datasets or the robustness of our face detection and landmark extraction methods.
For your case, where frames without landmarks occur often, interpolation can indeed help also make sure to build  Fallback Mechanisms .

**Comment by marekjg** [comment]
If I may ask, what was the dataset preparation process, have you used face-alignment for mouth region extraction and dlib for coordinates extraction as it is done in inference.py? I want to have dataset prepared as it was for training the ASR model.

**Comment by wissemkarous** [comment]
Exactly that's it, i've used face-alignment for mouth region extraction and dlib for coordinates extraction.

**Comment by marekjg** [comment]
Thanks! I think everything's clear now.
